import { requireAuth } from "@/lib/auth-session";
import { formatDateID, formatDateTimeID } from "@/lib/date-format";
import { prisma } from "@/lib/prisma";
import { RETURN_REASON_LABELS, type ReturnReason } from "@/lib/returns";
import { getSettings } from "@/lib/settings";
import { operatorLabel } from "@/lib/transaction-identity";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

// ── PDF constants ────────────────────────────────────────────────────────────
const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN_X = 40;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2; // 515
const NAVY = "#0F172A";
const MUTED = "#64748B";
const BORDER = "#E2E8F0";
const TEAL = "#0F9F8A";
const SOFT_TEAL = "#F0FDFB";
const SOFT_ROSE = "#FFF1F2";

// ── PDF primitives (identical pattern to existing PDF exports) ───────────────

function escapeText(value: string) {
  return value
    .replace(/[^\x20-\x7E]/g, " ")
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)");
}

function color(hex: string) {
  const v = hex.replace("#", "");
  const r = parseInt(v.slice(0, 2), 16) / 255;
  const g = parseInt(v.slice(2, 4), 16) / 255;
  const b = parseInt(v.slice(4, 6), 16) / 255;
  return `${r.toFixed(3)} ${g.toFixed(3)} ${b.toFixed(3)}`;
}

function text(
  value: string,
  x: number,
  y: number,
  size = 10,
  font = "F1",
  fill = NAVY,
) {
  return [
    "BT",
    `/${font} ${size} Tf`,
    `${color(fill)} rg`,
    `${x} ${PAGE_HEIGHT - y} Td`,
    `(${escapeText(value)}) Tj`,
    "ET",
  ].join("\n");
}

function rect(
  x: number,
  y: number,
  width: number,
  height: number,
  fill: string,
  stroke?: string,
) {
  const yy = PAGE_HEIGHT - y - height;
  if (!stroke) {
    return `${color(fill)} rg\n${x} ${yy} ${width} ${height} re f`;
  }
  return [
    `${color(fill)} rg`,
    `${color(stroke)} RG`,
    "0.8 w",
    `${x} ${yy} ${width} ${height} re B`,
  ].join("\n");
}

function line(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  stroke = BORDER,
) {
  return `${color(stroke)} RG\n0.8 w\n${x1} ${PAGE_HEIGHT - y1} m\n${x2} ${PAGE_HEIGHT - y2} l\nS`;
}

function truncate(value: string, max = 20) {
  return value.length > max ? `${value.slice(0, max - 2)}..` : value;
}

function rupiah(amount: number) {
  return `Rp ${Math.round(amount).toLocaleString("id-ID")}`;
}

function formatDate(date: Date) {
  return formatDateID(date);
}

function formatDateTime(date: Date) {
  return formatDateTimeID(date);
}

function returnReasonLabel(reason: string) {
  return RETURN_REASON_LABELS[reason as ReturnReason] ?? reason;
}

// ── PDF assembly (identical to existing exports) ─────────────────────────────

function buildPdfPages(pages: string[]) {
  const pageObjects = pages.flatMap((content, index) => {
    const pageObjectNumber = 5 + index * 2;
    const contentObjectNumber = pageObjectNumber + 1;
    return [
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectNumber} 0 R >>`,
      `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
    ];
  });

  const kids = pages.map((_, i) => `${5 + i * 2} 0 R`).join(" ");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    `<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    ...pageObjects,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];

  objects.forEach((obj, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;

  for (const offset of offsets) {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}

// ── Invoice-specific layout helpers ─────────────────────────────────────────

function pageFooter(page: number, total: number) {
  return [
    line(MARGIN_X, 800, PAGE_WIDTH - MARGIN_X, 800),
    text("Generated by Meijrverse POS", MARGIN_X, 818, 7.5, "F1", MUTED),
    text(`Halaman ${page} dari ${total}`, 500, 818, 7.5, "F1", MUTED),
  ].join("\n");
}

function invoiceHeader(storeName: string, invoiceNumber: string, printedAt: string) {
  return [
    // Store name top-left
    text(storeName.toUpperCase(), MARGIN_X, 44, 16, "F2", TEAL),
    text("Invoice Pembelian", MARGIN_X, 64, 10, "F1", MUTED),
    // Invoice number top-right
    text("Nomor Invoice", 390, 38, 7.5, "F1", MUTED),
    text(invoiceNumber, 390, 52, 9.5, "F2", NAVY),
    text("Dicetak", 390, 66, 7.5, "F1", MUTED),
    text(printedAt, 390, 80, 8, "F1", NAVY),
    // Divider
    line(MARGIN_X, 92, PAGE_WIDTH - MARGIN_X, 92, "#99D6CB"),
  ].join("\n");
}

function detailRow(label: string, value: string, y: number, col: "left" | "right") {
  const lx = col === "left" ? MARGIN_X : 310;
  const vx = col === "left" ? 140 : 420;
  return [
    text(label, lx, y, 8, "F1", MUTED),
    text(truncate(value, 22), vx, y, 8.5, "F2", NAVY),
  ].join("\n");
}

function sectionTitle(label: string, y: number) {
  return text(label.toUpperCase(), MARGIN_X, y, 9, "F2", NAVY);
}

function tableHeader(y: number) {
  return [
    rect(MARGIN_X, y, CONTENT_WIDTH, 24, NAVY),
    text("Produk", 52, y + 16, 7.5, "F2", "#FFFFFF"),
    text("SKU", 268, y + 16, 7.5, "F2", "#FFFFFF"),
    text("Qty", 328, y + 16, 7.5, "F2", "#FFFFFF"),
    text("Harga Satuan", 368, y + 16, 7.5, "F2", "#FFFFFF"),
    text("Subtotal", 510, y + 16, 7.5, "F2", "#FFFFFF"),
  ].join("\n");
}

function itemRow(
  y: number,
  productName: string,
  sku: string,
  qty: number,
  price: number,
  subtotal: number,
  discountAmount: number,
  discountLabel: string,
  discountReason: string,
  fill: string,
) {
  const hasDiscount = discountAmount > 0;
  const rowHeight = hasDiscount ? 40 : 24;

  const parts = [
    rect(MARGIN_X, y, CONTENT_WIDTH, rowHeight, fill, BORDER),
    text(truncate(productName, 32), 52, y + 15, 8, "F2", NAVY),
    text(truncate(sku || "-", 12), 268, y + 15, 8, "F1", MUTED),
    text(String(qty), 340, y + 15, 8, "F1", NAVY),
    text(rupiah(price), 555, y + 15, 8, "F1", NAVY),
    text(rupiah(subtotal), 555, hasDiscount ? y + 15 : y + 15, 8, "F2", NAVY),
  ];

  if (hasDiscount) {
    parts.push(
      text(`Diskon: -${rupiah(discountAmount)} ${discountLabel}`, 52, y + 30, 7, "F1", "#DC2626"),
    );
    if (discountReason) {
      parts.push(
        text(truncate(`(${discountReason})`, 40), 52, y + 42, 7, "F1", MUTED),
      );
    }
  }

  return { content: parts.join("\n"), height: rowHeight };
}

function totalRow(label: string, value: string, y: number, bold = false, color_?: string) {
  const font = bold ? "F2" : "F1";
  const labelColor = color_ ?? (bold ? NAVY : MUTED);
  const valueColor = color_ ?? (bold ? NAVY : NAVY);
  return [
    text(label, 330, y, 8.5, font, labelColor),
    text(value, 555, y, 8.5, font, valueColor),
  ].join("\n");
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const auth = await requireAuth(req);

  if (!auth.ok) {
    return auth.response;
  }

  const { id } = await params;
  const session = auth.session;

  // Fetch sale — cashiers can only access their own sales (same rule as invoice page)
  const [sale, settings] = await Promise.all([
    prisma.sale.findFirst({
      where: {
        id,
        ...(session.role === "cashier" ? { cashierId: session.sub } : {}),
      },
      include: {
        cashier: {
          select: {
            name: true,
            email: true,
            role: {
              select: { name: true, slug: true },
            },
          },
        },
        customer: {
          select: { name: true, phone: true, customerCode: true },
        },
        items: {
          select: {
            id: true,
            qty: true,
            price: true,
            subtotal: true,
            discountType: true,
            discountValue: true,
            discountAmount: true,
            discountReason: true,
            subtotalBeforeDiscount: true,
            product: {
              select: { name: true, sku: true },
            },
          },
          orderBy: { id: "asc" },
        },
        returns: {
          where: { returnType: "CUSTOMER_RETURN" },
          include: {
            items: {
              include: {
                product: { select: { name: true, sku: true } },
              },
              orderBy: { createdAt: "asc" },
            },
          },
          orderBy: { createdAt: "desc" },
        },
      },
    }),
    getSettings(),
  ]);

  if (!sale) {
    return NextResponse.json({ message: "Invoice tidak ditemukan." }, { status: 404 });
  }

  const paymentMethod = await prisma.paymentMethod.findUnique({
    where: { code: sale.paymentMethod },
    select: { name: true },
  });

  // ── Computed values ───────────────────────────────────────────────────────
  const moneyNumber = (v: unknown) => Math.round(Number(v ?? 0));

  const totalItemDiscount = sale.items.reduce(
    (acc, item) => acc + moneyNumber(item.discountAmount),
    0,
  );
  const subtotalBeforeDiscount = sale.items.reduce((acc, item) => {
    const stored = moneyNumber(item.subtotalBeforeDiscount);
    return acc + (stored > 0 ? stored : item.price * item.qty);
  }, 0);
  const subtotalBeforeLoyalty =
    sale.subtotalBeforeLoyalty > 0
      ? sale.subtotalBeforeLoyalty
      : Math.max(subtotalBeforeDiscount - totalItemDiscount, 0);
  const changeAmount = Math.max(sale.paidAmount - sale.subtotal, 0);
  const totalReturn = sale.returns.reduce(
    (acc, r) => acc + (r.totalRefund ?? 0),
    0,
  );

  const storeName = settings.storeName || "Toko Pancing";
  const printedAt = formatDateTime(new Date());
  const paymentMethodName = paymentMethod?.name ?? sale.paymentMethod;
  const cashierName = operatorLabel(sale.cashier);

  const statusLabel: string =
    sale.transactionStatus === "SUCCESS"
      ? "Lunas"
      : sale.transactionStatus === "PENDING"
        ? "Pending"
        : sale.transactionStatus === "CANCELLED"
          ? "Dibatalkan"
          : String(sale.transactionStatus);

  // ── Build PDF ─────────────────────────────────────────────────────────────
  const pages: string[][] = [];
  const page1: string[] = [];

  // Header
  page1.push(invoiceHeader(storeName, sale.invoiceNumber, printedAt));

  // Info grid
  let y = 112;
  page1.push(
    detailRow("Tanggal Transaksi", formatDateTime(sale.createdAt), y, "left"),
    detailRow("Kasir", cashierName, y, "right"),
  );
  y += 18;
  page1.push(
    detailRow("Metode Pembayaran", paymentMethodName, y, "left"),
    detailRow(
      "Pelanggan",
      sale.customer?.name ?? "Umum",
      y,
      "right",
    ),
  );
  y += 18;
  page1.push(
    detailRow("Status", statusLabel, y, "left"),
  );
  if (sale.customer?.phone) {
    page1.push(detailRow("HP Pelanggan", sale.customer.phone, y, "right"));
  } else if (sale.customer?.customerCode) {
    page1.push(detailRow("Kode Pelanggan", sale.customer.customerCode, y, "right"));
  }

  // If cancelled
  if (sale.transactionStatus === "CANCELLED") {
    y += 22;
    page1.push(
      rect(MARGIN_X, y, CONTENT_WIDTH, 28, SOFT_ROSE, "#FECACA"),
      text("Transaksi ini dibatalkan.", 52, y + 18, 9, "F2", "#DC2626"),
    );
    if (sale.cancelReason) {
      page1.push(text(`Alasan: ${truncate(sale.cancelReason, 50)}`, 52, y + 18, 8, "F1", "#DC2626"));
    }
  }

  // Items section
  y += 30;
  page1.push(
    line(MARGIN_X, y, PAGE_WIDTH - MARGIN_X, y),
  );
  y += 16;
  page1.push(sectionTitle("Item Pembelian", y));
  y += 18;
  page1.push(tableHeader(y));
  y += 24;

  pages.push(page1);

  // Item rows — may span pages
  let itemFill = "#FFFFFF";
  for (const item of sale.items) {
    const discountAmount = moneyNumber(item.discountAmount);
    const hasDiscount = discountAmount > 0;
    const discountLabel =
      item.discountType === "PERCENT"
        ? `(${moneyNumber(item.discountValue)}%)`
        : item.discountType === "FIXED"
          ? "(nominal)"
          : "";
    const rowHeight = hasDiscount ? (item.discountReason ? 50 : 40) : 24;

    if (y + rowHeight > 768) {
      pages[pages.length - 1].push(pageFooter(pages.length, 0));
      pages.push([
        invoiceHeader(storeName, sale.invoiceNumber, printedAt),
        sectionTitle("Item Pembelian (lanjutan)", 112),
        tableHeader(130),
      ]);
      y = 154;
    }

    const { content } = itemRow(
      y,
      item.product.name,
      item.product.sku ?? "",
      item.qty,
      item.price,
      item.subtotal,
      discountAmount,
      discountLabel,
      item.discountReason ?? "",
      itemFill,
    );
    pages[pages.length - 1].push(content);
    y += rowHeight;
    itemFill = itemFill === "#FFFFFF" ? "#F8FAFC" : "#FFFFFF";
  }

  // Totals section
  if (y + 130 > 768) {
    pages[pages.length - 1].push(pageFooter(pages.length, 0));
    pages.push([invoiceHeader(storeName, sale.invoiceNumber, printedAt)]);
    y = 112;
  }

  y += 14;
  pages[pages.length - 1].push(line(MARGIN_X, y, PAGE_WIDTH - MARGIN_X, y));
  y += 18;

  pages[pages.length - 1].push(
    totalRow("Subtotal sebelum diskon", rupiah(subtotalBeforeDiscount), y),
  );
  y += 16;

  if (totalItemDiscount > 0) {
    pages[pages.length - 1].push(
      totalRow("Total diskon item", `-${rupiah(totalItemDiscount)}`, y, false, "#DC2626"),
    );
    y += 16;
  }

  if (sale.loyaltyApplied && sale.loyaltyDiscountAmount > 0) {
    const loyaltyLabel = sale.loyaltyMilestone
      ? `Diskon loyalty (ke-${sale.loyaltyMilestone})`
      : "Diskon loyalty";
    pages[pages.length - 1].push(
      totalRow(loyaltyLabel, `-${rupiah(sale.loyaltyDiscountAmount)}`, y, false, "#DC2626"),
    );
    y += 16;
  }

  pages[pages.length - 1].push(line(330, y + 4, PAGE_WIDTH - MARGIN_X, y + 4));
  y += 14;

  // Grand total
  pages[pages.length - 1].push(
    rect(330, y - 4, CONTENT_WIDTH - 290, 24, SOFT_TEAL),
    totalRow("Grand Total", rupiah(sale.subtotal), y + 14, true),
  );
  y += 24;

  pages[pages.length - 1].push(
    totalRow("Dibayar", rupiah(sale.paidAmount), y + 4),
  );
  y += 18;

  if (changeAmount > 0) {
    pages[pages.length - 1].push(
      totalRow("Kembalian", rupiah(changeAmount), y + 2),
    );
    y += 16;
  }

  // Returns section
  if (sale.returns.length > 0) {
    y += 16;
    if (y + 60 > 768) {
      pages[pages.length - 1].push(pageFooter(pages.length, 0));
      pages.push([invoiceHeader(storeName, sale.invoiceNumber, printedAt)]);
      y = 112;
    }

    pages[pages.length - 1].push(
      line(MARGIN_X, y, PAGE_WIDTH - MARGIN_X, y),
    );
    y += 14;
    pages[pages.length - 1].push(sectionTitle("Retur Barang", y));
    y += 16;

    // Returns header
    pages[pages.length - 1].push(
      rect(MARGIN_X, y, CONTENT_WIDTH, 22, "#374151"),
      text("Tanggal", 52, y + 15, 7.5, "F2", "#FFFFFF"),
      text("Produk", 150, y + 15, 7.5, "F2", "#FFFFFF"),
      text("Qty", 360, y + 15, 7.5, "F2", "#FFFFFF"),
      text("Nilai Refund", 400, y + 15, 7.5, "F2", "#FFFFFF"),
      text("Alasan", 470, y + 15, 7.5, "F2", "#FFFFFF"),
    );
    y += 22;

    for (const saleReturn of sale.returns) {
      for (const rItem of saleReturn.items) {
        if (y + 24 > 768) {
          pages[pages.length - 1].push(pageFooter(pages.length, 0));
          pages.push([invoiceHeader(storeName, sale.invoiceNumber, printedAt)]);
          y = 112;
        }
        pages[pages.length - 1].push(
          rect(MARGIN_X, y, CONTENT_WIDTH, 24, "#FFF1F2", BORDER),
          text(formatDate(saleReturn.createdAt), 52, y + 16, 7.5, "F1", MUTED),
          text(truncate(rItem.product.name, 22), 150, y + 16, 7.5, "F1", NAVY),
          text(String(rItem.qty), 366, y + 16, 7.5, "F1", NAVY),
          text(rupiah(rItem.subtotal), 460, y + 16, 7.5, "F1", "#DC2626"),
          text(truncate(returnReasonLabel(saleReturn.reason), 14), 470, y + 16, 7.5, "F1", NAVY),
        );
        y += 24;
      }
    }

    if (totalReturn > 0) {
      y += 4;
      pages[pages.length - 1].push(
        totalRow("Total Nilai Retur", `-${rupiah(totalReturn)}`, y, true, "#DC2626"),
      );
    }
    y += 16;
  }

  // Thank-you note
  y += 20;
  if (y + 30 > 790) {
    pages[pages.length - 1].push(pageFooter(pages.length, 0));
    pages.push([invoiceHeader(storeName, sale.invoiceNumber, printedAt)]);
    y = 112;
  }
  pages[pages.length - 1].push(
    line(MARGIN_X, y, PAGE_WIDTH - MARGIN_X, y),
    text("Terima kasih sudah berbelanja!", MARGIN_X, y + 18, 9, "F2", TEAL),
  );

  // Fix page footers with final page count
  const total = pages.length;
  const finalPages = pages.map((page, index) =>
    [...page, pageFooter(index + 1, total)].join("\n"),
  );

  const filename = `invoice-${sale.invoiceNumber}.pdf`;

  return new NextResponse(new Uint8Array(buildPdfPages(finalPages)), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
